name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update daily file
        run: |
          echo "Commit on $(date)" >> daily.txt

      - name: Commit changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "h-fahad"
          git config --global user.email "fahadyounas10@gmail.com"
          git add .
          git commit -m "Daily commit on $(date)"
          git push https://$TOKEN@github.com/h-fahad/daily-commit-bot.git
